name: Expenses Manager

on:
  push:
    branches: [staging]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: copy env
        run: cd backend && cp .env.example .env && rm .env.testing
      - name: install deps
        run: cd backend && composer install
      - name: generate key
        run: cd backend && php artisan key:generate
      - name: DIR permissions
        run: cd backend && chmod -R 777 storage bootstrap/cache
      - name: create db
        run: |
          cd backend
          mkdir -p database
          touch database/database.sqlite
      - name: run tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
          CACHE_DRIVER: array
          SESSION_DRIVER: array
          QUEUE_DRIVER: sync
        run: |
          cd backend
          php artisan test